version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: campusme_db
    restart: always
    environment:
      POSTGRES_USER: campusme
      POSTGRES_PASSWORD: campusme123
      POSTGRES_DB: campusme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campusme_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campusme_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: campusme
      DATABASE_PASSWORD: campusme123
      DATABASE_NAME: campusme
      JWT_SECRET: campusme_secret_jwt_2026
      WT_EXPIRES_IN: 24h 
      PORT: 3000
    depends_on:
      - postgres
    networks:
      - campusme_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  campusme_network:
    driver: bridge
